-- Add verifier_rules table for new rule system
-- This table replaces the jsonb rules stored in verifier_users.servers

CREATE TABLE IF NOT EXISTS public.verifier_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    server_id text NOT NULL,
    server_name text NOT NULL DEFAULT '',
    channel_id text,
    channel_name text DEFAULT '',
    role_id text NOT NULL,
    slug text DEFAULT 'ALL',
    attribute_key text DEFAULT '',
    attribute_value text DEFAULT '',
    min_items bigint DEFAULT 0,
    message_id text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT verifier_rules_pkey PRIMARY KEY (id)
);

-- Add the main unique constraint for rules
ALTER TABLE public.verifier_rules 
ADD CONSTRAINT verifier_rules_unique_rule 
UNIQUE (server_id, channel_id, role_id, slug, attribute_key, attribute_value, min_items);

-- Grant permissions
GRANT ALL ON TABLE public.verifier_rules TO anon;
GRANT ALL ON TABLE public.verifier_rules TO authenticated;
GRANT ALL ON TABLE public.verifier_rules TO service_role;

GRANT ALL ON SEQUENCE public.verifier_rules_id_seq TO anon;
GRANT ALL ON SEQUENCE public.verifier_rules_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.verifier_rules_id_seq TO service_role;
