-- Initial legacy schema (from original dev)
-- This establishes the baseline that legacy users would have

CREATE TABLE IF NOT EXISTS public.verifier_servers (
  id text NOT NULL,
  name text NOT NULL,
  role_id text NULL,
  CONSTRAINT verifier_servers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.verifier_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id text NOT NULL,
  servers jsonb NOT NULL DEFAULT '{}'::jsonb,
  address text NOT NULL,
  CONSTRAINT verifier_users_pkey PRIMARY KEY (id, user_id),
  CONSTRAINT verifier_users_address_key UNIQUE (address),
  CONSTRAINT verifier_users_user_id_key UNIQUE (user_id)
);

-- Grant permissions
GRANT ALL ON TABLE public.verifier_servers TO anon;
GRANT ALL ON TABLE public.verifier_servers TO authenticated;
GRANT ALL ON TABLE public.verifier_servers TO service_role;

GRANT ALL ON TABLE public.verifier_users TO anon;
GRANT ALL ON TABLE public.verifier_users TO authenticated;
GRANT ALL ON TABLE public.verifier_users TO service_role;

GRANT ALL ON SEQUENCE public.verifier_users_id_seq TO anon;
GRANT ALL ON SEQUENCE public.verifier_users_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.verifier_users_id_seq TO service_role;
