-- Add verifier_user_roles table for role assignment logging
-- This table tracks which users have been assigned which roles

CREATE TABLE IF NOT EXISTS public.verifier_user_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id text NOT NULL,
    server_id text NOT NULL,
    role_id text NOT NULL,
    address text NOT NULL,
    assigned_at timestamp with time zone DEFAULT now(),
    CONSTRAINT verifier_user_roles_pkey PRIMARY KEY (id)
);

-- Unique constraint to prevent duplicate role assignments
ALTER TABLE public.verifier_user_roles 
ADD CONSTRAINT verifier_user_roles_user_id_server_id_role_id_key 
UNIQUE (user_id, server_id, role_id);

-- Grant permissions
GRANT ALL ON TABLE public.verifier_user_roles TO anon;
GRANT ALL ON TABLE public.verifier_user_roles TO authenticated;
GRANT ALL ON TABLE public.verifier_user_roles TO service_role;

GRANT ALL ON SEQUENCE public.verifier_user_roles_id_seq TO anon;
GRANT ALL ON SEQUENCE public.verifier_user_roles_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.verifier_user_roles_id_seq TO service_role;
