create table public.verifier_servers (
  id text not null,
  name text not null,
  role_id text null,
  constraint verifier_servers_pkey primary key (id)
) TABLESPACE pg_default;

create table public.verifier_users (
  id bigint generated by default as identity not null,
  user_id text not null,
  servers jsonb not null default '{}'::jsonb,
  address text not null,
  constraint verifier_users_pkey primary key (id, user_id),
  constraint verifier_users_address_key unique (address),
  constraint verifier_users_user_id_key unique (user_id)
) TABLESPACE pg_default;